version: 2

step-install: &step-install
  run: yarn install

step-build: &step-build
  run: yarn build

filter-tag: &filter-tag
  tags:
    only: /^v.*/

filter-tag-only: &filter-tag-only
  <<: *filter-tag
  branches:
    ignore: /.*/

jobs:
  lint:
    docker:
      - image: circleci/node:10.15.2-jessie-browsers-legacy
    steps:
      - checkout
      - *step-install
      - run: yarn lint
  build-win-linux:
    environment:
      GH_TOKEN: $GH_TOKEN
      CI: false
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - *step-install
      - *step-build
      - run: yarn dist:win-linux-publish

workflows:
  version: 2
  dist:
    jobs:
      - lint:
          filters:
            # <<: *filter-tag
            branches:
              only: electron
      - await-approval:
          type: approval
          filters:
            <<: *filter-tag-only
      - build-win-linux:
          requires:
            - await-approval
          # requires:
          #   - lint
          filters:
            <<: *filter-tag-only
