name: Publish electron

on:
  push:
    tags: v*

jobs:
  publish:
    environment: Publish
    runs-on: macos-10.15

    steps:
      - run: echo $GH_TOKEN
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'yarn'
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Package and publish
        run: yarn dist:gh-publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
